In [16]:
import numpy as np
import pandas as pd
import matplotlib as plot
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [3]:
dataset = pd.read_csv("Medical dataset.csv")

In [4]:
dataset

Unnamed: 0  RANDID  SEX  TOTCHOL  AGE  SYSBP  DIABP  CURSMOKE  CIGPDAY  \
0            1    2448    1    195.0   39  106.0   70.0         0        0   
1            2    2448    1    209.0   52  121.0   66.0         0        0   
2            3    6238    2    250.0   46  121.0   81.0         0        0   
3            4    6238    2    260.0   52  105.0   69.5         0        0   
4            5    6238    2    237.0   58  108.0   66.0         0        0   
..         ...     ...  ...      ...  ...    ...    ...       ...      ...   
64          65   54224    1    294.0   47  102.0   68.0         1       20   
65          66   55965    2    260.0   60  110.0   72.5         0        0   
66          67   55965    2    256.0   66  126.0   82.0         0        0   
67          68   55965    2    298.0   72  109.0   60.0         0        0   
68          69   63156    1    225.0   35  132.0   91.0         1       20   

      BMI  ...  CVD  HYPERTEN  TIMEAP  TIMEMI  TIMEMIFC  TIMECHD  TIMESTRK  \
0   26.97  ...    1         0    8766    6438      6438     6438      8766   
1     NaN  ...    1         0    8766    6438      6438     6438      8766   
2   28.73  ...    0         0    8766    8766      8766     8766      8766   
3   29.43  ...    0         0    8766    8766      8766     8766      8766   
4   28.50  ...    0         0    8766    8766      8766     8766      8766   
..    ...  ...  ...       ...     ...     ...       ...      ...       ...   
64  24.18  ...    1         0     430     430       430      430       430   
65  26.59  ...    0         1    8297    8766      8766     8297      8766   
66  25.43  ...    0         1    8297    8766      8766     8297      8766   
67  26.20  ...    0         1    8297    8766      8766     8297      8766   
68  26.09  ...    0         1    8766    8766      8766     8766      8766   

    TIMECVD  TIMEDTH  TIMEHYP  
0      6438     8766     8766  
1      6438     8766     8766  
2      8766     8766     8766  
3      8766     8766     8766  
4      8766     8766     8766  
..      ...      ...      ...  
64      430      430      430  
65     8766     8766     7951  
66     8766     8766     7951  
67     8766     8766     7951  
68     8766     8766        0  

[69 rows x 40 columns]

In [6]:
totCholMean = dataset["TOTCHOL"].mean()
totCholMean

246.41538461538462

In [7]:
ageMean = dataset["AGE"].mean()
ageMean

51.57971014492754

In [9]:
sysbpMean = dataset["SYSBP"].mean()
sysbpMean

135.80434782608697

In [10]:
bmiMean = dataset["BMI"].mean()
bmiMean

26.336323529411768

In [12]:
totCholMedian = dataset["TOTCHOL"].median()
totCholMedian

244.0

In [13]:
ageMedian = dataset["AGE"].median()
ageMedian

51.0

In [14]:
sysbpMedian = dataset["SYSBP"].median()
sysbpMedian

133.0

In [15]:
bmiMedian = dataset["BMI"]
bmiMedian

0     26.97
1       NaN
2     28.73
3     29.43
4     28.50
      ...  
64    24.18
65    26.59
66    25.43
67    26.20
68    26.09
Name: BMI, Length: 69, dtype: float64

In [19]:
dataset.corr()

Unnamed: 0    RANDID           SEX   TOTCHOL       AGE     SYSBP  \
Unnamed: 0    1.000000  0.982953 -7.718170e-03 -0.002286  0.004152 -0.066300   
RANDID        0.982953  1.000000 -5.611637e-03 -0.013541 -0.003537 -0.099407   
SEX          -0.007718 -0.005612  1.000000e+00  0.017389  0.149993 -0.170288   
TOTCHOL      -0.002286 -0.013541  1.738936e-02  1.000000  0.167828 -0.230222   
AGE           0.004152 -0.003537  1.499928e-01  0.167828  1.000000  0.214214   
SYSBP        -0.066300 -0.099407 -1.702879e-01 -0.230222  0.214214  1.000000   
DIABP        -0.107412 -0.119176 -2.984460e-01 -0.244827 -0.127514  0.788014   
CURSMOKE      0.129540  0.150145 -8.199201e-02  0.159184 -0.227569 -0.075900   
CIGPDAY       0.108671  0.124460 -9.168444e-03  0.169659 -0.136267 -0.132128   
BMI          -0.086330 -0.056205  2.038519e-01 -0.118181  0.215510  0.365472   
DIABETES      0.089206  0.079348  1.507557e-01  0.065738  0.196228  0.324574   
BPMEDS       -0.129420 -0.162294  3.760589e-02  0.026378 -0.120581  0.253713   
HEARTRTE     -0.110480 -0.152465 -1.356094e-01 -0.012740 -0.232400  0.227421   
GLUCOSE       0.177929  0.172413  2.458945e-01  0.016351  0.350327  0.199985   
educ         -0.117384 -0.074730 -1.206660e-02 -0.159816 -0.208875 -0.173870   
PREVCHD      -0.109599 -0.111001  8.574929e-02 -0.082797  0.277073  0.078092   
PREVAP       -0.109599 -0.111001  8.574929e-02 -0.082797  0.277073  0.078092   
PREVMI             NaN       NaN           NaN       NaN       NaN       NaN   
PREVSTRK           NaN       NaN           NaN       NaN       NaN       NaN   
PREVHYP       0.074231  0.031461 -3.279680e-01 -0.056478  0.110423  0.699342   
TIME          0.037338 -0.015571  3.583913e-02  0.006246  0.582778  0.206175   
PERIOD        0.040181 -0.011916  3.772466e-02  0.015423  0.585024  0.211098   
HDLC          0.332417  0.308835  2.898781e-01 -0.022827  0.132574 -0.021478   
LDLC          0.117791  0.096262  1.115137e-01  0.930716  0.456997 -0.252954   
DEATH         0.104947  0.085822  2.803060e-01  0.003927 -0.054158  0.024163   
ANGINA        0.165601  0.204980  1.976424e-01  0.010023  0.506878 -0.128279   
HOSPMI        0.074893  0.091452 -1.091089e-01  0.011339  0.016088 -0.042235   
MI_FCHD      -0.073463 -0.052838 -8.868040e-18 -0.058906 -0.027849  0.236806   
ANYCHD        0.045236  0.087894  1.274118e-01 -0.042994  0.303441  0.115614   
STROKE       -0.229885 -0.180900  1.221694e-01 -0.080042  0.266172  0.258812   
CVD          -0.172940 -0.131516  5.598925e-02 -0.091125  0.096363  0.336472   
HYPERTEN      0.381483  0.356963  5.241424e-02 -0.098451  0.080616  0.380651   
TIMEAP        0.021696  0.006468 -2.295842e-01  0.051299 -0.134857 -0.005399   
TIMEMI       -0.014840 -0.032755 -1.288263e-01 -0.001588  0.108863  0.064693   
TIMEMIFC      0.053617  0.032609 -1.724124e-01  0.032843  0.127740 -0.072756   
TIMECHD       0.127881  0.106391 -2.276947e-01  0.113673 -0.094998 -0.092702   
TIMESTRK     -0.052509 -0.069454 -1.796116e-01 -0.033276  0.063045  0.009809   
TIMECVD       0.067875  0.044113 -1.757306e-01  0.037425  0.105615 -0.088442   
TIMEDTH      -0.070931 -0.084880 -1.766796e-01 -0.040215  0.084450  0.028920   
TIMEHYP      -0.253029 -0.222959  3.307155e-01  0.116425  0.061627 -0.609888   

               DIABP  CURSMOKE   CIGPDAY       BMI  ...       CVD  HYPERTEN  \
Unnamed: 0 -0.107412  0.129540  0.108671 -0.086330  ... -0.172940  0.381483   
RANDID     -0.119176  0.150145  0.124460 -0.056205  ... -0.131516  0.356963   
SEX        -0.298446 -0.081992 -0.009168  0.203852  ...  0.055989  0.052414   
TOTCHOL    -0.244827  0.159184  0.169659 -0.118181  ... -0.091125 -0.098451   
AGE        -0.127514 -0.227569 -0.136267  0.215510  ...  0.096363  0.080616   
SYSBP       0.788014 -0.075900 -0.132128  0.365472  ...  0.336472  0.380651   
DIABP       1.000000 -0.004448 -0.063809  0.211326  ...  0.094573  0.320991   
CURSMOKE   -0.004448  1.000000  0.801180 -0.578527  ... -0.204285  0.192315   
CIGPDAY    -0.063809

In [17]:
# Label Encoder

In [18]:
le = LabelEncoder()

In [21]:
totCholLE = le.fit_transform(dataset["TOTCHOL"])
ageLE = le.fit_transform(dataset["AGE"])
sysbpLE = le.fit_transform(dataset["SYSBP"])
bmiLE = le.fit_transform(dataset["BMI"])

In [23]:
totCholLE

array([ 4,  8, 26, 30, 22, 24, 36, 15, 19, 37, 48, 49, 17, 18, 12,  7, 12,
       45, 49, 46, 30, 41, 35, 15, 29,  9, 27, 49, 40, 25, 42, 38, 47, 15,
        0, 16,  5, 31, 13, 19, 14, 11, 40,  4, 32, 10,  4,  6,  1,  3, 23,
       16,  2, 33, 49, 20, 34, 36, 11, 28, 21, 33, 44, 39, 42, 30, 28, 43,
       15], dtype=int64)

In [24]:
ageLE

array([ 2, 14,  8, 14, 20, 10, 16, 22, 27,  8, 13, 20,  5, 11, 17, 24, 28,
        7, 13, 19, 14, 20, 25,  5, 11, 17, 12, 18, 23,  5,  8, 14,  3,  9,
       15,  2,  8, 13,  1, 10, 16, 21,  8,  1,  6, 11,  3,  9, 15,  4, 10,
       16,  5, 11, 17, 14, 20, 25, 14, 20, 25,  6, 12, 18,  9, 21, 26, 29,
        0], dtype=int64)

In [25]:
sysbpLE

array([ 3, 11, 11,  2,  4, 17, 30, 37, 50, 19,  5, 40, 49, 48, 49, 26, 36,
        0,  6,  7, 31, 21, 46, 43, 34, 47, 22, 17, 10, 20, 32, 45, 14, 10,
       14,  9, 24, 30, 29, 26, 28, 33,  8, 12, 27, 44, 27, 42, 39,  4, 12,
       15, 13, 16, 18, 35, 43, 41, 21, 38, 37, 25, 23, 21,  1,  7, 15,  5,
       21], dtype=int64)

In [26]:
bmiLE

array([41, 65, 47, 49, 45, 27, 27, 46, 52, 16, 19, 24, 53, 56, 54, 59, 64,
        4, 10,  9, 35, 28, 30, 20, 42, 48, 14,  0,  8, 43, 34, 37, 55, 44,
       39, 11,  1, 25,  2, 12,  5, 15, 18, 17, 51, 57, 40, 33, 36,  3,  6,
        3, 50, 62, 63, 61, 60, 58, 26, 13, 22,  7, 21, 13, 23, 38, 29, 32,
       31], dtype=int64)